default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: app_<%= ENV.fetch("RAILS_ENV") { 'development' } %>

development:
  <<: *default

test:
  adapter: test

integration:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

